# Basic options
title:  Ágoston Reguly
author:  Ágoston Reguly
email:  reguly_agoston@phd.ceu.edu
description:  Personal website
logo:  /assets/images/logo.jpg
github_username:  regulyagoston

# Building settings
theme: jekyll-theme-minimal

# Additional
# google_analytics:
# show_downloads: true
logo: /assets/img/logo.jpg

