project:
  type: website
  output-dir: docs

website:
  title: "Ágoston Reguly"
  google-analytics: "G-BGV4MVV5TE"
  sidebar:
    tools:
      - icon: twitter
        href: https://twitter.com/AgostonReguly
      - icon: github
        href: https://github.com/regulyagoston
    style: "docked"
    search: true
    contents:
      - index.qmd
      - section: "About me"
        contents:
          - cv.qmd
          - teaching.qmd
      - section: "Research"
        contents:
          - papers.qmd
    

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



