---
title: "CV"
format:
  html:
    minimal: false
---

# Curriculum Vitae
*Last update: 2025/09/19*

[Download CV](https://regulyagoston.github.io/assets/img/CV.pdf)


## Current Positions

- Assistant Professor -- Corvinus University at Budapest (CUB), Institute of Economics
- Affiliated Researcher -- Georgia Institute of Technology (GT), FSIL at Scheller College of Business

## Previous Positions and Research Experiences

- *Visiting Professor* -- Central European University (CEU), Department of Business and Economics (2023-2025)
- *Postdoctoral research fellow* -- Georgia Institute of Technology (GT), FSIL at Scheller College of Business (2022-2023)
- *Junior Researcher* -- Institute of Economics, Centre for Economic and Regional Studies (CERS)
- *Research Assistant* - at CEU, collaborating with University of College London.
	- Conducted research on econometric theory and applications of models where the dependent or explanatory variables are discretized due to surveys, but in fact, they are continuous. During the research, I have collaborated with [MaaSLab](https://www.ucl.ac.uk/bartlett/energy/research/energy-and-transport/maaslab) at the University of College London, a research group focusing on public transportation and faces challenges due to discretization when modeling.

## Published and Working Papers

- [Discovering Heterogeneous Treatment Effects in Regression Discontinuity Designs](https://arxiv.org/abs/2106.11640)
	- The paper proposes a causal supervised machine learning algorithm to uncover treatment effect heterogeneity in classical regression discontinuity designs. Extending Athey and Imbens (2016) with leaf-by-leaf regression, I develop a criterion for building an honest “regression discontinuity tree”, where each leaf of the tree contains the RD estimate of treatment conditional on the values of some pre-treatment covariates.
- [Modelling with Sensitive Variables](https://arxiv.org/abs/2403.15220) - *Joint with Felix Chan and László Mátyás*
- [When and How Much Do Fixed Effects Matter?](https://link.springer.com/chapter/10.1007/978-3-031-49849-7_2) - *Joint with Felix Chan and László Mátyás*
	- In: Matyas, L. (eds),The Econometrics of Multi-dimensional Panels 2nd Edition, Springer (2024), Chapter 2, pp. 39-60.
- [Long-term market performance of merger and acquisitions](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4742401) (WP) - *Joint with Sudheer Chava*


## Published Papers

- [When and How Much Do Fixed Effects Matter?](https://link.springer.com/chapter/10.1007/978-3-031-49849-7_2) - *Joint with Felix Chan and László Mátyás*
	- In: Matyas, L. (eds),The Econometrics of Multi-dimensional Panels 2nd Edition, Springer (2024), Chapter 2, pp. 39-60.
- [The Use of Machine Learning in Treatment Effect Estimation](https://link.springer.com/chapter/10.1007/978-3-031-15149-1_3) -- *jointly with Robert Lieli (CEU) and Yu-Chin Hsu (National Central University and National Chengchi University)*
	- In: Chan, F., Matyas, L. (eds), Econometrics with Machine Learning. Advanced Studies in Theoretical and Applied Econometrics, vol 53. Springer, Cham (2022), pp. 79-109.

## Conferences and presentations
- Annual Financial Markets and Liquidity Conference (2024)
	- *Long-term market performance of merger and acquisitions*
- European Economic Association (EEA) and Econometric Society European Meeting (ESEM) 2024 Summer Conference
	- *Long-term market performance of merger and acquisitions*
- European Economic Association (EEA) and Econometric Society European Meeting (ESEM) 2021 Summer Conference
	- EEA: *Heterogeneous Treatment Effects in Regression Discontinuity Designs* 
	- ESEM: *Modelling with Discretized Continuous Dependent Variable*
- International Association for Applied Econometrics
    - 2021: *Heterogeneous Treatment Effects in Regression Discontinuity Designs* 
	- 2019: *Modelling with Discretized Ordered Choice Covariates* - Cyprus
 - Brownbag Seminar Series at the Department of Economics and Business
    - 2021: *Heterogeneous treatment effects in regression discontinuity designs*
    - 2020: *Ordered Choice Modelling with Discretized Continuous Dependent Variable*
    - 2019: *Modelling with Discretized Ordered Choice Covariates*
 - Hungarian Society of Economist Yearly Conference
    - 2014: *Forecasting the Hungarian Nelson-Siegel Yield Curve with Mixed Factor Model*  - Budapest

## Administrative Experience

- Organizer of the Empirical Brownbag Seminar at the Institute of Economics at Corvinus University of Budapest
	- Discuss ongoing ideas and help each other to refine and publish empirical papers in the topic of Economics and Finance.
- Organizer of the *Econometrics Reading Group* at the Department of Economics and Business at CEU.
	- Organized reading group events for Ph.D. students and faculty members, covering various papers from the field of econometrics. We held meetings in two weeks frequency.

## Teaching experience

 - **Econometrics I** - BA in Applied Economics at CUB
	- From 2023 each Fall. English and Hungarian
 - **Data Analysis** - MS in Business Analytics at CEU
    - 2024/25 - Lecturer for Data Analysis 2 
	- 2023/24 - Lecturer for Data Analysis 3
	- 2020/21 - Lecturer for Data Analysis 1 and 2 
    - 2018/19 – Teaching Assistant for Data Analysis 3 and 4. (lecturer: Gábor Békés)
 - **Machine Learning for Finance – Vertically Integrated Project** - Georgia Tech 
 - **Coding 1: Data Management and Analysis with R** - MS in Business Analytics at CEU
    - 2020/21 and 2021/22 - Lecturer
 - **Data course** - Executive Master of Business Art (EMBA) at CEU
    - 2020/21 - Joint lecturer with Anand Murugesan
 - **Mathematics and Advanced Excel Pre-session** MS in Finance at CEU
    - 2019/20, 2020/21 and 2021/22 - Lecturer
 - **Mathematical Methods for Economists** - MA in Economics
    - 2017/18 - Teaching Assistant

## Education
 - 2016-2021: Central European University, Budapest and Vienna, Ph.D. in Economics
	- Advisors: Róbert Lieli and László Mátyás
	- Graduated with Summa Cum Laude
	- PhD Thesis: Three Essays on Econometrics
 - 2012-2015: MA in Economic Analysis at Budapest University of Technology and Economics (BME)
    - Graduated with Summa Cum Laude, ECTS weighted average: 4.65/5; ECTS: 162 of 120
 - 2012 Sept – 2013 Feb: ERASMUS scholarship in Germany
    - Otto-Friedrich Universität Bamberg, focusing on behavioral economics
 - 2009-2012: BA in Management and Business Administration at BME
    - Graduated with excellent degree, ECTS weighted average 4.02/5; ECTS: 256 of 210
 - 2003-2009 Franciscan High School of Szentendre, Hungary 

## Awards and Scholarships
 - **Award for Advanced Doctoral Studies**, 2019 CEU’s rector award for outstanding Ph.D. students
 - **Pro Scientia Golden Medal**, 2013 academic award for young scholars, given at the Hungarian Academy of Sciences.
 - **National Scientific Students' Association Conference Awards (OTDK)**
	- 2015 1st Prize in economics section
	- 2013 3rd Prize in economics section
	- 2011 1st Prize in economics section
	- 2011 Award of the Hungarian Economic Review
	- 2011 Short listed for the best presentation
 - **University Scientific Students' Association Conference Awards**
	- 2014 Academic award of Rector Magnificus 
	- 2014 1st Prize in economics section
	- 2014 1st Prize in finance section, selected for National Scientific Students' Association Conference
	- 2011 Memorial award of Heller Farkas by Heller Farkas Foundation
	- 2011 1st Prize, in economics section, selected for National Scientific Students' Association Conference
	- 2010 Award of Pro Progressio Fundation for enhancing young scholars
	- 2010 1st Prize, in economics section, selected for National Scientific Students' Association Conference
- **Other Awards**
	- 2013 Economist’s Forum's Young Scientist Award for the best article of the year
	- 2013 Felkai András Memorial Scholarship for support training of young talents
	- 2013 Outstanding students’ award at the Budapest University of Technology and Economics
	- 2012 & 2013 Special Extended Scholarship of Economy and Social Sciences Faculty of Budapest University of Technology and Economics
	- 2012 Hungarian Republic Fellowship (József Nádor)

## Publications

### Publication from my BA/MA studies

- *Constructing Hungarian Zero-Coupon Yield Curve Models* - 2015
	- National Scientific Students’ Association Conference (in Hungarian)
- *Forecasting the Hungarian Nelson-Siegel Yield Curve with Mixed Factor Model* - 2014
	- Conference Paper: Hungarian Society of Economist Yearly Conference (in Hungarian)
- *Happiness of Economic Man* - 2014, joint with: K. Martin´as, Zs. Gilányi and V. Poór
	- In Francesco Sarracino (Eds): The Happiness Compass, Chapter 19 Nova Science Publishers
- *Reappraisal of Rational Choice Theory* - 2013, joint with K. Martinás
	- Interdisciplinary Description of Complex Systems (INDECS), 11(1)
- *Behavioral models of pension systems, part II.* - 2013
	- Economists’ Forum, 2013. April
- *Behavioral models of pension systems, part I.* - 2012
	- Economists’ Forum, 2012. February


## Working experience
 - **Consultancy**
	- Analysis on government security market for Hungarian State Treasury (2019)
 - **Hungarian Government Debt Management Agency** (2013 - 2016)
	- I was responsible for periodical reports of the government security market and developing new methodologies for analyzing and forecasting the Hungarian government yield curve. Furthermore, I have contributed to the development of the new portfolio model.

## Summer schools
 - 2015 July: Cambridge Econometrics Summer School, Timberlake Ltd.
 - 2014 July: Oxford Econometrics Summer School at Aix-en-Provance, Timberlake Ltd.

## Skills
 - **Language**
    - *English*: TOEFL ibt: 104; B2 certificates: general (2008) and economics specific (2011)
    - *German*: B2 certificate, general, 2014
 - **IT skills**: 
	- *Proficient*: MatLab, R
	- *Advanced*: Python, Microsoft Office programs
	- *Intermediate*: Stata, Eviews, SPSS, Mathematica
- **Driving license**: 
    - A and B categories
- **Hobbies**:
	- I have been sailing for fourteen years, and achieved 1st award in the National Competition of Jolle 25 class in 2007, 2009 and 2010.
	- Nowadays in my spare time I have turned to mountaineering and rock climbing. Among many peaks in the Tatras and the Austrian Alps, in 2018 I have climbed Mount Blanc via the Cosmiques route. 


<a href="/assets/img/CV.pdf" download="reguly_cv"> Download CV

[back](./)
