---
title: "Papers"
---
*Last update: 2026/08/31*

# Working Papers

- *Central Bank Communication in a Small Open (Unorthodox) Economy* - joint with Marton Kovacs
	- [working paper](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=7344804) 
- *Perverse Effects of Imperfectly Enforced Price Controls* - joint with [Boris Knapp](https://sites.google.com/view/borisknapp)
	-[working paper](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=6436778) 
- *The Long-run Performance of Mergers and Acquisitions* - joint with [Sudheer Chava](https://scholar.google.com/citations?user=AXYf-i8AAAAJ&hl=en)
	-[working paper](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4742401)
- *Discovering Heterogeneous Treatment Effects in Regression Discontinuity Designs* - R&R at Journal of Applied Econometrics
	-[working paper](https://arxiv.org/abs/2106.11640), [MatLab codes](https://github.com/regulyagoston/RD_tree)
- *Machine Learning* - joint with [László Mátyás (CEU)](https://laszlo.matyas.ceu.edu/) & [Essie Maasoumi (Emory)](https://sites.google.com/view/esfandiarmaasoumi/home)
	-[book chapter WIP] in *A History of Econometrics: The Challenge of Remaining Relevant* Editors: Matyas L, Pirotte A, Publisher: Springer, Expected publication: 2027 Spring
- *Data Privacy* - joint with [Zsigmond Pálvölgyi (CUB)](https://zsigmond-palvolgyi.github.io/)
	-[book chapter WIP] in *A History of Econometrics: The Challenge of Remaining Relevant* Editors: Matyas L, Pirotte A, Publisher: Springer, Expected publication: 2027 Spring

# Published papers

- *Modelling with Sensitive Variables* - joint work with with [Felix Chan (Curtin)](https://profiles.curtin.edu.au/3929-felix-chan) and [László Mátyás (CEU)](https://laszlo.matyas.ceu.edu/)
	- [publised in AStA Advances in Statistical Analysis](https://doi.org/10.1007/s10182-026-00566-5)
- *When and How Much Do Fixed Effects Matter?* (2024) - joint work with with [Felix Chan (Curtin)](https://profiles.curtin.edu.au/3929-felix-chan) and [László Mátyás (CEU)](https://laszlo.matyas.ceu.edu/)
	- [published book chapter](https://link.springer.com/chapter/10.1007/978-3-031-49849-7_2), in Matyas, L. (eds) The Econometrics of Multi-dimensional Panels. Advanced Studies in Theoretical and Applied Econometrics, vol 54. Springer, Cham.
- *The Use of Machine Learning in Treatment Effect Estimation* (2022) - joint work with Robert Lieli (CEU) and Yu-Chin Hsu (National Central University and National Chengchi University)
  - [published book chapter](https://link.springer.com/chapter/10.1007/978-3-031-15149-1_3), in: Chan, F., Matyas, L. (eds), Econometrics with Machine Learning. Advanced Studies in Theoretical and Applied Econometrics, vol 53. Springer, pp. 79-109

### Publication from my BA/MA studies

- *Constructing Hungarian Zero-Coupon Yield Curve Models, Using Global Optimalization Methods* (2015)
	- [published paper](https://akk.hu/download?path=9f434155-e7f9-427f-9006-97fc5c08a140.pdf) - 
	*only in Hungarian*

- *Macroeconometric Modelling of Inflation, Wages and Money Supply: Implementing David F. Hendry's reduction theory to the Hungarian Economy between 1995 and 2014* (2015)
	- MA thesis - *only in Hungarian*

- *Forecasting the Hungarian Nelson-Siegel Yield Curve with Mixed Factor Model* (2014) 
	- Conference Paper: Hungarian Society of Economist Yearly Conference (2014, December 19) - *only in Hungarian*

- *Happiness of Economic Man* (2014) – joint work with Katalin Martinás, Zsolt Gilányi, Veronika Poór
	– The Happiness Compass, Chapter 19 Nova Science Publishers, editors: Francesco Sarracino 

- *Reappraisal of Rational Choice Theory* (2013) – joint work with Katalin Martinás
	- Interdisciplinary Description of Complex Systems (INDECS), 11(1)

- *Behavioral models of pension systems, part II.* (2013)
	- Economists’ Forum - *only in Hungarian*

- *Behavioral models of pension systems, part I.* (2012)
	- Economists’ Forum - *only in Hungarian*

- *Behavioral models of pension systems* (2012)
	- BA Thesis - *only in Hungarian*
