---
title: "Courses"
---

Updated: 2024/07/29

## Courses at Corvinus (CUB)

- Econometrics I for Applied Economics
- Project 3 for Applied Economics, this is a thesis writing course for BA students

## Teaching at Central European University (CEU)

- Data Analysis 1, 2 or 3 for Business Analytics at CEU
    - Based on [Békés-Kézdi (2021): Data Analysis for Business, Ecnonomics and Policy - CUP](https://gabors-data-analysis.com/)
    - Course descriptions for [DA-1](https://courses.ceu.edu/courses/2023-2024/data-analysis-1-exploration-business-analytics-track) (2020-21), [DA-2](https://courses.ceu.edu/courses/2023-2024/data-analysis-2-finding-patterns-regressions-business-analytics-track) (2020-21, 2024-25) or [DA-3](https://courses.ceu.edu/courses/2023-2024/data-analysis-3-prediction-and-introduction-machine-learning) (2023-24)
- Coding 1: Data Management and Analysis with R for Business Analytics at CEU (2020/21 and 2021/22 Fall)
    - [Materials and codes](https://github.com/CEU-Economics-and-Business/ECBS-5208-Coding-1-Business-Analytics), [course description](https://courses.ceu.edu/courses/2020-2021/coding-1-data-management-and-analysis-r)
    - In 2021/22 Fall I have tought similar material for Finance students.
- Data course for Executive MBA at CEU (2020 Summer) - Jointly with Anand Murugesan
    - [webpage](https://emba.ceu.edu/) for EMBA at CEU
- Mathematics and Informatics Pre-session for MS in Finance at CEU (2019/20 and 2020/21 Fall)
    - [course description](https://courses.ceu.edu/courses/2020-2021/presession-finance-mathematics-excel-4)

## Other teaching experiences

- Machine Learning for Financial Markets course, that is a [Vertically Integrated Project](https://vip.gatech.edu/), now a similar course is run under the name of [AI for Financial Markets](https://vip.gatech.edu/teams/entry/1279/), which also includes NLP methods.